[project]
name = "juicer-pump"
version = "0.1.0"
description = "Python wrapper for serial communication with the juicer pump."
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["pyserial>=3.5"]

[dependency-groups]
dev = ["ipython>=9.8.0"]

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = ["src"]
include = ["juicer*"]

[project.scripts]
juicer-test-connection = "test_connection:main"
juicer-unit-test = "unit_test:_main"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.ruff.lint.per-file-ignores]
"src/juicer/__init__.py" = ["F401"]
