[project]
name = "juicerpy"
version = "0.1.0"
description = "Python wrapper for serial communication with the juicer."
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["ipython>=8.38.0", "pyserial>=3.5"]

[project.scripts]
juicer-test-connection = "test_connection:main"
juicer-unit-test = "unit_test:_main"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
